### ISSUE TITLE
plz help me

### ISSUE THREAD

**Issue by vesvese55x** [dbghelp/html-epg-viewer#1]
https://www.bevy.be/bevyfiles/turkeypremium2.xml bu xlm epg'sini göstermiyor. bunu da destekleyecek şekilde günceller misiniz? https://dbghelp.github.io/epg.html?file=https://www.bevy.be/bevyfiles/turkeypremium2.xml burdan inceleyebilirsiniz...  çoook güzel yapmışsınız emeğinize sağlık

**Comment by dbghelp** [comment]
The EPG link is blocked by CORS (this got nothing to do with the program)

![CORS](https://github.com/user-attachments/assets/c6ae17f8-6f3e-40d3-8591-332ec930797a)

One way to bypass it is to use web browser extensions like "CORS Unblock": [https://chromewebstore.google.com/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?hl=en-US&utm_source=ext_sidebar](url)

The EPG loaded fine except there's no channel logo and programme thumbnail as it's not included in the XML itself:
![plugin](https://github.com/user-attachments/assets/f230e09c-8583-4dce-a2aa-cfc68ed13a86)

You can also clone the XML to your github, this way, there won't be any CORS issue

**Comment by dbghelp** [comment]
if there are no further questions, I will proceed to close this
